verbose: false,
instrumentation:
    root: ./src
    extensions: ['.js', '.jsx']
    excludes: [
        './utils/dev-server.js'
    ]
reporting:
    watermarks:
        statements: [50, 70]
        lines: [50, 70]
        functions: [50, 70]
        branches: [50, 70]
check:
     global:
       branches   : 80
       functions  : 80
       lines      : 80
       statements : 80
