verbose: false,
instrumentation:
    root: [ ./src, ./server ]
    extensions: ['.js', '.jsx']
    excludes: [
        'utils/dev-server.js',
        '**/components/**',
        '**/containers/**'
    ]
reporting:
    watermarks:
        statements: [50, 70]
        lines: [50, 70]
        functions: [50, 70]
        branches: [50, 70]
check:
     global:
       branches   : 30
       functions  : 30
       lines      : 30
       statements : 30
