const lti_payload = {
  oauth_version: '1.0',
  oauth_nonce: '8f08fda8bb00725ae75b21f489ce3d8c',
  oauth_timestamp: '1531150298',
  oauth_consumer_key: 'cu-moodle',
  user_id: '6',
  lis_person_sourcedid: '',
  roles: 'Instructor',
  context_id: '5',
  context_label: 'FC',
  context_title: 'Flow course',
  resource_link_title: 'Quodl',
  resource_link_description: '',
  resource_link_id: '2',
  context_type: 'CourseSection',
  lis_course_section_sourcedid: 'AAAA',
  lis_result_sourcedid: '{"data":{"instanceid":"2","userid":"6","typeid":"5","launchid":1376771222},"hash":"84d3c205c64418794a7fbbbde6246e640c667cdbf40ad2cc23f3a2831224250b"}',
  lis_outcome_service_url: 'http://localhost:8888/moodle35/mod/lti/service.php',
  lis_person_name_given: 'Lecturer',
  lis_person_name_family: 'Two',
  lis_person_name_full: 'Lecturer Two',
  ext_user_username: 'lecturer2',
  lis_person_contact_email_primary: 'lecturer2@test.com',
  launch_presentation_locale: 'en',
  ext_lms: 'moodle-2',
  tool_consumer_info_product_family_code: 'moodle',
  tool_consumer_info_version: '2018051700',
  oauth_callback: 'about:blank',
  lti_version: 'LTI-1p0',
  lti_message_type: 'basic-lti-launch-request',
  tool_consumer_instance_guid: 'localhost',
  tool_consumer_instance_name: 'Moodle 3.5',
  tool_consumer_instance_description: 'Moodle 3.5',
  custom_module: 'JJJJ',
  launch_presentation_document_target: 'window',
  launch_presentation_return_url: 'http://localhost:8888/moodle35/mod/lti/return.php?course=5&launch_container=4&instanceid=2&sesskey=eDUKsNPfzj',
  oauth_signature_method: 'HMAC-SHA1',
  oauth_signature: 'VCT7ygyFGpMgVCsEPFW8Y0/UCSY='
};
